### ISSUE TITLE
Test SR on my own images, and not dataset?

### ISSUE THREAD

**Issue by zelenooki87** [gladzhang/ART#1]
Hi.
Thank you for promising project.
I want upscale photos of mine which are not kind of any dataset. 
Is it any way doable? And how to do it?
Do I need to upscale to the bicubic first?
Please provide more infos in readme.txt
Thanks

**Comment by gladzhang** [comment]
Thanks for your interest. At first, you can use our method to upscale your own photos. You do not need to upscale the original images in advance. In practice, you should upload your images into an independent folder in `datasets`. Then you should change the yml file in the folder `options/test` to use your provided data as testing data. Lastly, remember to download our provided pre-trained models and run the testing scripts to get the visual results. We will keep updating the contents of this repository. Thanks for your attention.

**Comment by zelenooki87** [comment]
In terms of environment conda and pretrained models did it correctly.

Only way working for me but not as expected good, is to as GR- use original photos and for  LR using downscaled photos.
if I set in yml file gt and lq path the same, I got a shape error in dimensions about datasets.


could you please upload example of yml for custom data test? for 4x upscale
thank you very much!

**Comment by gladzhang** [comment]
I have not described the solution clearly. In fact, the original 'basicsr/test.py' file needs to calculate the PSNR and SSIM value so the gt path must be provided in yml file. If you only want to obtain the visual outputs of the original photos, you need to change the 'test.py' file. The idea is that you only use the 'dataroot_lq' and 'network_g' information in yml file to get the input data and proposed model. Then you can load the model parameters and get the outputs and save them as files. Of course, another way is that you provide the upscale photos with correct image size and use them as gt files.

**Comment by zelenooki87** [comment]
Getting cuda OOM error on second way "upscale photos with correct image size and use them as gt files."
Could you modify code for --tile inference?
Tried to change test.py file without success. Could you please more advice?

**Comment by gladzhang** [comment]
Hi, we have provided the instructions about how to apply our model to upscale any provided photos in README file. We provide the new yml files in the folder `options/apply' and you can find the changed parts there. We also provide an example photo and you can run the given scripts to have a try. Remember to download the pre-trained models in advance. Best wishes.
