### ISSUE TITLE
Missing highly relevant literature 

### ISSUE THREAD

**Issue by vztu** [gladzhang/ART#5]
Hi @gladzhang,

Thanks for sharing and open-sourcing the great work.

Just want to raise your attention that your proposed idea is highly relevant to our ECCV paper ["MaxViT: multi-axis vision transformer"](https://arxiv.org/pdf/2204.01697.pdf) where we propose similar local and dilated global attention mechanisms. 

![image](https://user-images.githubusercontent.com/43280278/199193333-7bf7c6a5-716f-4f4b-bf81-e756ef46bb06.png)

The ideas are derived from our previous CVPR paper ["MAXIM: Multi-Axis MLP for Image Processing"](https://arxiv.org/abs/2201.02973) which also share similar ideas. 

I'd be appreciated if you can mention these highly relevant papers in your next edit version. Thanks!

**Comment by yulunzhang** [comment]
Hi @vztu 

Thanks for reminding us about your excellent work. It's glad to see the local and global attention idea works well in several image restoration applications. As you suggest, we would like to discuss more related works including your papers in our next version (will revise the arXiv version soon). 

Best,
Yulun

**Comment by gladzhang** [comment]
Hi [@vztu](https://github.com/vztu)

Thanks again for your suggestion. MaxViT and MAXIM are both excellent works. To the best of our knowledge, it is very meaningful to mention and discuss these two works in our main paper. We have updated a [new version arXiv](https://arxiv.org/abs/2210.01427). You can go to the website to find it soon. Still thanks for your advice and attention.

Best wishes.

**Comment by vztu** [comment]
Thanks a lot for the prompt updates on Arxiv @yulunzhang @gladzhang! I appreciate that you have included our works in your revision. Glad to see that this simple local and global idea can work on a broad range of vision tasks. Anyway, nice work on another Transformer arch for low-level vision. Good luck with your submission~
