### ISSUE TITLE
Tks for your brilliant works!!! I am curious about did you trained ART on DIV2K dataset ?

### ISSUE THREAD

**Issue by longphamkhac** [gladzhang/ART#9]

**Comment by gladzhang** [comment]
Thanks! We have not trained ART on DIV2K dataset so far. We will consider this in the future.

**Comment by longphamkhac** [comment]
And have you trained with another batchsize, for instance batchsize = 16, and did the result worse than 32 ?

**Comment by gladzhang** [comment]
In our experiments, we set the batchsize to 32. According to the common experience, the larger batchsize may bring better results.
